services:
  postgres:
    image: postgres:15.1-alpine
    container_name: restaurant-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: restaurant-redis
    ports:
      - 6379:6379
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data/_data
  rabbitmq:
    image: rabbitmq:3.12.2-management
    container_name: restaurant-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  app:
    build: .
    container_name: restaurant-app
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; ./start.sh"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
  celery_worker:
    build: .
    container_name: restaurant-celery-worker
    command: celery -A background.celery worker --loglevel=info
    environment:
      - CELERY_BROKER=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      - CELERY_BACKEND=redis://${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - rabbitmq
volumes:
  postgres-data:
  redis-data:
