services:
  postgres:
    container_name: restaurant-test-postgres
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant
  app:
    container_name: restaurant-test-app
    build: .
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; ./test.sh"
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@postgres:5432/restaurant
      - POSTGRES_ASYNC_URI=postgresql+asyncpg://postgres:postgres@postgres:5432/restaurant
    ports:
      - 8000:8000
    depends_on:
      - postgres
