services:
  postgres:
    image: postgres:15.1-alpine
    container_name: test-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant
  redis:
    image: redis:7
    container_name: test-redis
    ports:
      - 6380:6379
    command: >
      --requirepass redis
  app:
    build: .
    container_name: test-app
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; ./test.sh"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_PASSWORD=redis
    depends_on:
      - postgres
      - redis
