services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres-data:
