services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant
    volumes:
      - local-postgres-data:/var/lib/postgresql/data
  app:
    build: .
    pull_policy: always
    environment:
      - POSTGRES_URI=postgresql+asyncpg://postgres:postgres@postgres:5432/restaurant
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: ["./scripts/wait-for-it.sh", "postgres:5432", "--", "./start.sh"]

volumes:
  local-postgres-data:
