services:
  postgres:
    image: postgres:15.1-alpine
    container_name: restaurant-test-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant
      - TZ=Europe/Moscow
  redis:
    image: redis:7
    container_name: restaurant-test-redis
    ports:
      - 6380:6379
    command: >
      --requirepass redis
    environment:
      - TZ=Europe/Moscow
  app:
    build: .
    container_name: restaurant-test-app
    command: >
      bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done;
      alembic upgrade head;
      pytest"
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_PASSWORD=redis
      - TZ=Europe/Moscow
    depends_on:
      - postgres
      - redis
