"""add discount

Revision ID: 042708222378
Revises: c3a5c7255b6a
Create Date: 2023-08-13 02:24:33.063041

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '042708222378'
down_revision = 'c3a5c7255b6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('discount', sa.Numeric(precision=6, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'discount')
    # ### end Alembic commands ###
