"""change cascade

Revision ID: 1da8d3bf953b
Revises: f204437d0598
Create Date: 2023-07-29 10:02:01.249371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da8d3bf953b'
down_revision = 'f204437d0598'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
